### ISSUE TITLE
Get this working on Android

### ISSUE THREAD

**Issue by pneun** [svendahlstrand/web-serial-api#1]
Hi,

is there a way to get this working on my Android Phone?
I have Chrome 86 installed and flag #enable-experimental-web-platform-features enabled.
But there is no navigator.serial available .

Thank you, Philipp

**Comment by svendahlstrand** [comment]
Hello Philipp,

Yes, it should be possible if you use the [web-serial-polyfill](https://github.com/google/web-serial-polyfill).
