### ISSUE TITLE
Dimmer sample seems broken

### ISSUE THREAD

**Issue by ScruffR** [svendahlstrand/web-serial-api#2]
When I try to connect  a COM port either virtual USB Serial (CDC) or via a BlueTooth COM I always get this error in the browser console (Chrome 97.0.4692.71 (Official Build) (64-bit); Edge Version 97.0.1072.55 (Official build) (64-bit))
```
Uncaught (in promise) TypeError: 
  Failed to execute 'open' on 'SerialPort': 
  Failed to read the 'baudRate' property from 'SerialOptions': 
  Failed to read the 'baudRate' property from 'SerialOptions': 
  Required member is undefined.
    at getReader (dimmer.html:45:20)
```

The first issue I found was that your code is using `baudrate`  where it now needs to be `baudRate`.

**Comment by svendahlstrand** [comment]
Thanks! It's now fixed with e5711f154b4557664d14f54fece4820d15a75b96.
